### ISSUE TITLE
Compilation error on aarch64

### ISSUE THREAD

**Issue by g0ddest** [KalessinD/perl_crypt_xxhash#1]
When building on aarch64 I have an error:

```
#0 3.622 c++: error: unrecognized command-line option '-msse2'
#0 3.623 c++: error: unrecognized command-line option '-msse4.2'
```

that is specified here: https://github.com/KalessinD/perl_crypt_xxhash/blob/main/Build.PL#L15

**Comment by KalessinD** [comment]
@g0ddest , sorry for taking so long.

Should be fixed in v0.07: sse instructions will be ignored for armv7l and aarch64

**Comment by KalessinD** [comment]
should be fixed.
closing

**Comment by KalessinD** [comment]
should be fixed.
closing
